version: '3.9'

services:
  oracledb:
    build:
      context: ./docker
      dockerfile: Dockerfile.oracle
    container_name: oracledb
    environment:
      - ORACLE_PWD=123456
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ../docker/Dockerfile
    container_name: weatherguard-app
    depends_on:
      - oracledb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracledb:1521/xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - backend

volumes:
  oracle-data:

networks:
  backend:
