services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      - POSTGRES_DB=weatherguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: weatherguard-app
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/weatherguard
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
